### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/stac-geoparquet#21]
Hey @TomAugspurger,
would you be happy if we'd release the current status as 0.3.0 or so?

**Comment by TomAugspurger** [comment]
Sure.

We'll need to bump https://github.com/stac-utils/stac-geoparquet/blob/main/stac_geoparquet/__init__.py#L2.

And we'll need to figure out the upload to PyPI permissions. In TomAugspurger/stac-geoparquet I had a secret to upload to PyPI. IIRC, the `stac-utils` organization might have a secret we can use, similar to https://github.com/stac-utils/pystac/blob/ebe5c6b32c38c9f4a2acfb7936fc84c026f67482/.github/workflows/release.yml#L28. I'm not sure if that secret is available in this repo or not (I can't seem to view secrets. Can you?)

**Comment by m-mohr** [comment]
I bumped the version number.

I see a TWINE_PASSWORD, PYPI_STACUTILS_PASSWORD and PYPI_STACUTILS_USERNAME in the repo/org secrets.

So should it be
```
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
```

or 
```
          TWINE_USERNAME: ${{ secrets.PYPI_STACUTILS_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_STACUTILS_PASSWORD }}
```

in the publish.yml? Or does both work? Then it should work already. @TomAugspurger

**Comment by m-mohr** [comment]
Also updated the repo URL in various places: https://github.com/stac-utils/stac-geoparquet/commit/09f545c7aac938ba7d879f67cebc5052ca382ff3

**Comment by TomAugspurger** [comment]
PyPI acutally has a new feature for "trusted publishers" that I'm trying out https://docs.pypi.org/trusted-publishers/adding-a-publisher/.

**Comment by TomAugspurger** [comment]
With https://github.com/stac-utils/stac-geoparquet/pull/22 merged, I *think* things are set up to upload a release on GitHub releases. I probably messed something up, but we'll see. I'll tag a release now.

**Comment by TomAugspurger** [comment]
https://github.com/stac-utils/stac-geoparquet/actions/runs/5600077559/jobs/10241944419 is the GitHub action building and uploading the release to PyPI.

**Comment by m-mohr** [comment]
Close :-)
It works locally for me though, weird...

**Comment by TomAugspurger** [comment]
Maybe https://github.com/stac-utils/stac-geoparquet/commit/e073fe08c026696f2a7328a743294e1f0358e73a got it. I'll try a 3.0.1.

**Comment by m-mohr** [comment]
Looks like we need to change this?
https://github.com/stac-utils/stac-geoparquet/issues/21#issuecomment-1642111936

**Comment by TomAugspurger** [comment]
I'm going to try one more time. I think I had `publish.yaml` in one place and `publish.yml` in another.

**Comment by TomAugspurger** [comment]
Success! https://pypi.org/project/stac-geoparquet/0.3.2/

**Comment by m-mohr** [comment]
Thank you, Tom!
