### ISSUE TITLE
Specify how to refer to a STAC geoparquet file from a STAC json

### ISSUE THREAD

**Issue by cholmes** [stac-utils/stac-geoparquet#29]
So far I think we've speced how to create the GeoParquet file, but a common use case is to use the GeoParquet file to mirror the stac catalog. It'd be good to have a clear recommendation for how you link to that file from STAC JSON. I suspect it's in the Collection - an asset or a link, I could see an argument for either. Should specify what 'rel' to use, etc. Then clients could know that there's a way to query.

**Comment by alexgleith** [comment]
I think it makes more sense as an asset than as a link. Then there could be more ancillary information too.

**Comment by cholmes** [comment]
Yeah, I think I lean asset. The only thing that gives me pause with asset is that the other assets are often like an image of the whole collection, or metadata of the collection, while the stac-geoparquet sorta _is_ the collection - it's an alternate representation of the same items you can follow links down into. But the fact PC went with asset is a strong point in that direction - we'd need a good reason to do something different.

**Comment by TomAugspurger** [comment]
Closed by #30
