### ISSUE TITLE
Align spec with GeoParquet 1.1

### ISSUE THREAD

**Issue by kylebarron** [stac-utils/stac-geoparquet#34]
The `bbox` field is currently listed as `Struct of Floats`. It would be nice to have more detail on this. How should the struct columns be named? Can they be float32 or only float64? Now that bounding boxes are part of the GeoParquet 1.1 spec, we should align the spec here with that.

**Comment by TomAugspurger** [comment]
> Now that bounding boxes are part of the GeoParquet 1.1 spec, we should align the spec here with that.

Agreed. I don't see any reason to diverge from the GeoParquet spec.
