### ISSUE TITLE
Test files with sequence of items

### ISSUE THREAD

**Issue by kylebarron** [stac-utils/stac-geoparquet#39]
Right now, the only JSON files in the fixtures directory are individual STAC items. It would be great to have a sequence of files from a single collection so that we could test equality of round-tripping from JSON to Parquet and back to JSON. There's a `naip.parquet` file in the fixtures with 5 rows but it's not clear where that file was created from.

Any preference over where these test Items should come from?

**Comment by TomAugspurger** [comment]
If possible, I'd like to minimize the number of binary files in the repo (and maybe remove `naip.parquet` when possible).

Happy to add a handful of JSON / ndjson files with some more STAC items for testing.

No preference on the source.
