### ISSUE TITLE
pyarrow error when running the example in README

### ISSUE THREAD

**Issue by zstatmanweil** [stac-utils/stac-geoparquet#55]
When I run the example in the README, or a similar example on my own data, I am getting this error:

```
TypeError: Cannot convert pyarrow.lib.ChunkedArray to pyarrow.lib.RecordBatch
```

My package versions:

```
arrow==1.3.0
pyarrow==16.1.0
stac_geoparquet==0.5.1
```
However, `stac_geoparquet.to_geodataframe(items, dtype_backend='pyarrow')` works fine

**Comment by zstatmanweil** [comment]
Ah, I see PR #53 from last week is related to this. Perhaps following the documentation will work when a new version is released? So this can probably can be closed if that is the case.

**Comment by kylebarron** [comment]
Yeah, I think that's correct. For now, maybe consult the documentation from the latest release tag? https://github.com/stac-utils/stac-geoparquet/tree/0.5.1

**Comment by zstatmanweil** [comment]
That does the trick. Thanks!

**Comment by kylebarron** [comment]
Awesome. I'm working on updating the documentation (with a website!) in #65, and then we'll probably publish the next minor release
